CREATE EXTENSION cube;

CREATE TABLE public.encoding
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 ),
    encodings cube NOT NULL,
    student_email character varying(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT student_email FOREIGN KEY (student_email)
        REFERENCES public.student (email) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
);

ALTER TABLE public.encoding
    OWNER to root;
